import { Inter } from "next/font/google";
import "./css/Layout.css";
import Provider from "./_provider";
import Sidebar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main
            style={{
              height: "100%",
              width: "100%",
            }}
          >
            <Sidebar />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
