import { Inter } from "next/font/google";
import "./css/Layout.css";
import Providers from "./_provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main
            style={{
              height: "100%",
              width: "100%",
            }}
          >
            {children}
          </main>
          <ReactQueryDevtools />
        </Providers>
      </body>
    </html>
  );
}
